### ISSUE TITLE
Crash on boot, itch.io windows build

### ISSUE THREAD

**Issue by qwertyuu** [Apostolique/Mitten#12]
Used version 2.0.5 from itch.io on windows. Using Windows 10.

![image](https://github.com/Apostolique/Mitten/assets/3145639/aa97d32b-4d2a-41ad-9d0d-669a4949f2ea)

**Comment by Apostolique** [comment]
Oops! I pushed a fix in version 2.0.6. Most likely I'll have to refactor the code a bit to avoid issues like that in the future.

**Comment by qwertyuu** [comment]
![image](https://github.com/Apostolique/Mitten/assets/3145639/995b5601-5a44-4b5e-9c25-be33bbfe6f95)
